### ISSUE TITLE
Stoping grab data.

### ISSUE THREAD

**Issue by darhanger** [wakatime/office-wakatime#11]
More then week ago Waka stop grab data from all IDE and from office stuff to. Try write to waka support but they ignore.

![image](https://user-images.githubusercontent.com/22445395/138215558-b8920639-4b60-49a7-8204-3aa5072c90c2.png)

**Comment by gandarez** [comment]
fyi @alanhamlett

**Comment by alanhamlett** [comment]
@darhanger please set `debug = true` in your `~/.wakatime.cfg` file then let me know if you see any error messages in your `~/.wakatime.log` file.

**Comment by darhanger** [comment]
@alanhamlett what i seen in this file? Its clean. Try it before. On Work place it clean, at home i just haven't it

**Comment by darhanger** [comment]
@alanhamlett got only Word. Notepad++ still not work

[Log.txt](https://github.com/wakatime/office-wakatime/files/7402724/Log.txt)

**Comment by alanhamlett** [comment]
> @alanhamlett got only Word. Notepad++ still not work
> 
> [Log.txt](https://github.com/wakatime/office-wakatime/files/7402724/Log.txt)

That `log.txt` shows Word is working, but there are no logs in there related to Notepad++. That must mean the Notepad++ extension isn't loading correctly. Can you try re-installing it?

**Comment by alanhamlett** [comment]
Closing this, and let's continue in wakatime/notepadpp-wakatime#44.
