### ISSUE TITLE
Excel add-in causes 'Microsoft Excel is waiting for another application to complete an OLE action' error

### ISSUE THREAD

**Issue by richardcarrigan** [wakatime/office-wakatime#12]
After installing the Microsoft Excel add-in, I sometimes receive the error "Microsoft Excel is waiting for another application to complete an OLE action" when trying to close a file, and the only way to successfully close the file is to choose "Cancel".

Disabling the add-in fixes the error, so I am sure that it's due to this add-in and not any others.

Thanks!

**Comment by DavyDeCoster** [comment]
+1 on this

**Comment by LloydLore** [comment]
I have encountered the same issue

**Comment by c3r38r170** [comment]
Confirm this in Office 2013.

**Comment by gandarez** [comment]
A new [version ](https://github.com/wakatime/office-wakatime/releases/tag/2.2.0)has been released.
