### ISSUE TITLE
Disable install for all users

### ISSUE THREAD

**Issue by xmha97** [wakatime/office-wakatime#16]
"Install for all users" disabled for Word and Excel addon.
Please also disable for PowerPoint installer.
![image](https://user-images.githubusercontent.com/23485114/163567438-62e50f3d-67ad-4f2b-833f-4c42f555b61d.png)
Thanks

**Comment by 0day404** [comment]
> Word 和 Excel 插件禁用“为所有用户安装”。 另请禁用 PowerPoint 安装程序。 谢谢 ![图像](https://user-images.githubusercontent.com/23485114/163567438-62e50f3d-67ad-4f2b-833f-4c42f555b61d.png)

Thank you very much, solved my problem

**Comment by gandarez** [comment]
A new [version ](https://github.com/wakatime/office-wakatime/releases/tag/2.2.0)has been released.
