### ISSUE TITLE
when time this project will update to latest wakatime-cli version

### ISSUE THREAD

**Issue by loyio** [wakatime/office-wakatime#17]
does this project accept pull request 
<img width="653" alt="CleanShot 2022-04-18 at 16 39 57@2x" src="https://user-images.githubusercontent.com/32695256/163782078-932fa3fe-2b5b-4b66-a898-42c7d3b44df9.png">

**Comment by alanhamlett** [comment]
We just need to update the shared extension utils package to version `4.1.0` here:

https://github.com/wakatime/office-wakatime/blob/f38939d93e579bb401a10543951a3b3c8dff95fb/WordWakaTimeAddin/packages.config#L25
