### ISSUE TITLE
Word freezes when I close the window

### ISSUE THREAD

**Issue by jmmenah** [wakatime/office-wakatime#19]
When I have the plugin active, the window freezes when I close the app , specially when i have been using Word for hours.

**Comment by LNKLEO** [comment]
> When I have the plugin active, the window freezes when I close the app , specially when i have been using Word for hours.

i meet this problem, even with a one minute unsaved document

**Comment by gandarez** [comment]
A new [version ](https://github.com/wakatime/office-wakatime/releases/tag/2.2.0)has been released.
