### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by devnetkc** [wakatime/office-wakatime#2]
This supports windows only.  Any chance of getting a version that works for both operating systems?

**Comment by nixoncode** [comment]
+1 for this

**Comment by tfflyer** [comment]
+1

**Comment by jdiazcoto** [comment]
+1

**Comment by avelarfe** [comment]
Yea, I'd like to use it on MacOS...

**Comment by TedTschopp** [comment]
The real issue here is that they decided to use add-ons that Microsoft has said are/will be deprecated and thus this add-on is Windows only.  If they used the new Add-On approach for Office, they wouldn't have this issue.  So what we should be pushing for is Wakatime to use the new API for Office Add-ons so it will work on any implementation of Office, not just the Windows one.

https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins

**Comment by gandarez** [comment]
If I'm not mistaken it doesn't have support for events like saving documents, opening documents and so on.

**Comment by hsieh123** [comment]
+1 for this feature.

**Comment by jonathanfan-ee** [comment]
+1 for this

**Comment by elijaholmos** [comment]
adding another +1

**Comment by songhn233** [comment]
+1 feature request

**Comment by eac7219** [comment]
+1 feature request

**Comment by DerekErb** [comment]
+1 feature request

The fact that these plug-ins are Windows-only should be made clearer on the Github welcome page. This would avoid us having to download and attempt to install it to find out that it will not work.

**Comment by Alpha-Girl** [comment]
+1 need it！

**Comment by tanjuntao** [comment]
> +1 feature request
> 
> The fact that these plug-ins are Windows-only should be made clearer on the Github welcome page. This would avoid us having to download and attempt to install it to find out that it will not work.

Can't agree more from a macOS user.

**Comment by DerekErb** [comment]
> +1 feature request

Adding on to my previous comment. This repository needs a README.MD file which could provide such valid information as which versions of Office and which platforms are compatible with this plug-in.

**Comment by fbao-fudan** [comment]
+1

**Comment by alanhamlett** [comment]
We can't support Mac because we can't use Microsoft's new JavaScript-based plugin framework, since it doesn't support running our extension code in the background on user events such as `cursor moved` or `file saved`.

I've added a note to the readme saying it only works on Windows.

**Comment by fredzannarbor** [comment]
Not good enough.  What percentage of your users use Mac? Got to be pretty high.

**Comment by DerekErb** [comment]
There are probably more of us developers who work on Mac than you may believe.

When I work on documentation in Word I have to calculate my time spent manually.

When I work on files to import in databases in Excel I have to calculate manually.

Luckily I use memtime which is, miraculously, able to automatically follow both my phpStorm usage and my Office usage on my Mac. I don't completely understand why they can and you can't.

**Comment by alanhamlett** [comment]
You can use our [Mac Desktop App](https://wakatime.com/mac) as an alternative. We just need to know the `bundleId` of the office apps to enable tracking them.
