### ISSUE TITLE
Install into Word and Excel Office 365

### ISSUE THREAD

**Issue by kmedri** [wakatime/office-wakatime#22]
Hi, I have tried all of the options in the closed Issues, and still cannot seem to get a connection working.
It does not appear in my plugin status page. The same is happening for Excel. I have logging in Word however not sure what I should be looking for.
I get no errors and I can see the WakaTime option in the menu bar. The API key is added into the options ok.
<img width="758" alt="image" src="https://user-images.githubusercontent.com/1414665/199386271-3c9bebfc-3460-4ea9-a183-fab48d9c225f.png">

**Comment by Bugo72** [comment]
Hi, 
Same problem here.

**Comment by gandarez** [comment]
A new [version ](https://github.com/wakatime/office-wakatime/releases/tag/2.2.0)has been released.
