### ISSUE TITLE
MS Office Add-in API Key Formatting

### ISSUE THREAD

**Issue by lawrence-dubowitz** [wakatime/office-wakatime#23]
The current implementation of WakaTime MS Office add-ins do not accept the API key in [waka__***...] format. In order for the API key to be accepted by the Office add-in, the "waka__" prefix needs to be stripped leaving the rest of the API key.

**Comment by haruna-nagayoshi** [comment]
@lawrence-dubowitz 
I have same problem, but resolved because of you. Thanks.

**Comment by jattebury** [comment]
Seems to be the same issue as [here](https://github.com/wakatime/notepadpp-wakatime/issues/53#issuecomment-1377560511) with the fix [here](https://github.com/wakatime/notepadpp-wakatime/commit/cbe13eb7169f549fa926616a8dd6c1bbc2956b96). 

Confirmed in the same issue in the Word addin (and presumably others) in SettingForm.Designer.cs and ApiKeyForm.Designer.cs, should be an easy fix.
