### ISSUE TITLE
Not tracking activity

### ISSUE THREAD

**Issue by saeid4x** [wakatime/office-wakatime#24]
i insalled word plugin and enter api-key. but it not added to my dashboard.

**Comment by qishenzhou** [comment]
same here

**Comment by Philipp1297** [comment]
Same problem still there.
API-Key is valid. 
Editor Integration is also not visible in the Plugin Status

**Comment by biggujo** [comment]
Same here

**Comment by charveey** [comment]
Same thing here

**Comment by hyunicode** [comment]
Same problem still there.
API-Key is valid.
Editor Integration is also not visible in the Plugin Status

**Comment by muety** [comment]
Yep, got the same problem here!

**Comment by muety** [comment]
Possibly, upgrading to the latest [extension utils](https://github.com/wakatime/nuget-wakatime-shared-extension-utils) version (2.2.0 -> 4.2.0) would help already? Any thoughts on this, @alanhamlett?

**Comment by guibranco** [comment]
Same problem here.

Tried to remove the `waka_` prefix from API Key. In both cases, no tracking activity was sent to Wakatime API (monitored via Fiddler4)...

**Comment by Mohamed3nan** [comment]
same :/

**Comment by DRaz1r** [comment]
Same Problem.

**Comment by ghost** [comment]
Any clue guys? I entered valid key by deleted waka_ but still it didn't appear in my dashboard

**Comment by DRaz1r** [comment]
> Any clue guys? I entered valid key by deleted waka_ but still it didn't appear in my dashboard

Same

**Comment by Jozoooooo** [comment]
SAME
