### ISSUE TITLE
`Please enter valid Api Key.` when trying to change to new wakatime key

### ISSUE THREAD

**Issue by Snailedlt** [wakatime/office-wakatime#29]
![image](https://github.com/wakatime/office-wakatime/assets/43886029/43dee5be-7b5a-4b4c-8c73-93bc04441e7a)
The key is copied directly from wakatime and put into excel without any proxies... Still I get the error `Please enter valid Api Key.`

**Comment by ValeeDS** [comment]
I had the same issue, in another thread it was stated that the issue was to use the "waka_" in the beginning. So you should delete it when adding the api key

**Comment by Snailedlt** [comment]
@ValeeDS thanks for the tip, however I already tried that and it doesn't work with nor without the waka_ prefix

**Comment by s-c-a-l-l-o-p** [comment]
Same here, even if I remove the waka_ prefix. I tested with: 

- 2.1.1
- 2.1.0
- 2.0.0

Windows 11 x64
Excel 2016

**Comment by alievrenkut** [comment]
Removing **waka_** prefix is not working because you first paste into input box which removes last 5 characters.

You should only copy non **waka_** part and past it. It will work.
