### ISSUE TITLE
New cli version available

### ISSUE THREAD

**Issue by ValeeDS** [wakatime/office-wakatime#30]
I have this message on my Plugin Status dashboard. I tried to re-install the plugin for excel as states the instructions but it didn't work, I also tried to manually install the cli; I did, but it changed nothing on the status. The release for office is from Jul 4, 2021, but the one for the cli is from yesterday (Aug 30, 2023), is this related to the issue?

<img width="479" alt="image" src="https://github.com/wakatime/office-wakatime/assets/88331793/31403f1e-73af-448f-a91b-9f1d57d5c04f">
<img width="613" alt="image" src="https://github.com/wakatime/office-wakatime/assets/88331793/4e23051a-5272-44d9-82f4-209c1c589b6d">

**Comment by alanhamlett** [comment]
Probably because [shared-extension-utils](https://github.com/wakatime/nuget-wakatime-shared-extension-utils) is still on an old version (2.1.0).
