### ISSUE TITLE
Support for Hakatime

### ISSUE THREAD

**Issue by jmangelson** [wakatime/office-wakatime#4]
Hi, I would like to use your plugin for Hakatime.

The main need would be to modify the URL to which heartbeats are published. 

Is there someway to expose that functionality?

**Comment by hypervtechnics** [comment]
This is already working as the extension uses the configuration file in your home directory

**Comment by gandarez** [comment]
Hi, you might set your own custom url into `~/.wakatime.cfg` file. For reference please see this [doc](https://github.com/wakatime/wakatime-cli/blob/develop/USAGE.md#ini-config-file).
