### ISSUE TITLE
Word Add-in Issues

### ISSUE THREAD

**Issue by vahidmafi** [wakatime/office-wakatime#6]
Hi

1. The add-in will not show up in Microsoft Word when you install it for everyone. It should be installed for the user "Just me"
2. After successful installation of add-in and setting the API key, it will not counted toward any section of the dashboard (e.g. editors, mins).

**Comment by calee0219** [comment]
As my experience, for office 2019, including powerpoint, excel, and word need to install as "Just me" mode or you will not able to see the "WakaTime" tag on the navbar.

But it still can install for "everyone" mode. So I'm not sure if using "everyone" mode also works or not.

**Comment by gandarez** [comment]
Just released a new version disabling install for all users.
