### ISSUE TITLE
Can I use it on MacOS ？

### ISSUE THREAD

**Issue by GnaixEuy** [wakatime/office-wakatime#9]
How do I use plug-ins in office on MacOS system? Will they be supported in the future?

**Comment by rjdbcm** [comment]
I have yet to find a way to get it to install on MacOS. Would be nice.

**Comment by DiegoCao** [comment]
> I have yet to find a way to get it to install on MacOS. Would be nice.0

May I ask how can it be installed in MacOS?

**Comment by gandarez** [comment]
Not yet but we plan to support it.

**Comment by gandarez** [comment]
Duplicate of https://github.com/wakatime/office-wakatime/issues/2
